### ISSUE TITLE
Updating documents

### ISSUE THREAD

**Issue by jhk0530** [Merck/pkglite#49]
Hi, thanks for nice package. Honestly, I think it's super cool.

As I understand, I can bring some R package as text file to isolated development environments.

I was checking out the Get started and Articlec and had a question, so I raised an issue.

In [*Curate File Collections*](https://merck.github.io/pkglite/articles/filecollection.html) , there's code below which I understand as
"You can select your R package's contents as you want to pkglite" not only the `file_default`

```r
library("pkglite")
pkg <- system.file("examples/pkg1/", package = "pkglite")

fc <- merge(
  pkg %>% collate(file_root_core()),
  pkg %>% collate(file_r()),
  pkg %>% collate(file_r(), file_man())
)
```

If so, shouldn't the last line have `collate(file_r(), file_man())` with `file_r()` as a duplicate?
Because it's already included in line before. 

So I was confused about last line is meant to be show `collate` function can take multiple parameters or typo.
If is intended, it may good to give comment like `#collate can have multiple file_* functioins` or remove `file_r()`.

```r
fc <- merge(
  pkg %>% collate(file_root_core()),
  pkg %>% collate(file_r()),
  pkg %>% collate(file_r(), file_man()) # you can use multiple file collections in collate
)

fc <- merge(
  pkg %>% collate(file_root_core()),
  pkg %>% collate(file_r()),
  pkg %>% collate(file_man()) 
)
```

Thanks !

**Comment by nanxstats** [comment]
Yes, it's intentional.

> This operation returns the **union** of the files.
