### ISSUE TITLE
Only list files but not folder 

### ISSUE THREAD

**Issue by elong0527** [Merck/pkglite#7]
Would you think this line of code can be used to list files? Just want to avoid folders

```
setdiff(list.files(), list.dirs(recursive = FALSE, full.names = FALSE))
```

https://stackoverflow.com/questions/22069095/r-get-list-of-files-but-not-of-directories

**Comment by nanxstats** [comment]
Nice! Thanks a lot for spotting this.

For cross-platform compatibility reasons, I would feel safer though with that functional solution using `utils::file_test()` (https://stackoverflow.com/a/22069867) than with a set operation.

I think we can make this update in 0.1.2.

**Comment by nanxstats** [comment]
Fixed by https://github.com/Merck/pkglite/commit/b042747f05b742b4ada692c5ecabada29d4f99f8
