### ISSUE TITLE
Add SAS binary file formats to dictionary

### ISSUE THREAD

**Issue by nanxstats** [Merck/pkglite#8]
I would like to add SAS binary data extensions to `ext_binary()` in the [dictionary](https://github.com/Merck/pkglite/blob/master/R/dictionary.R), as some packages might contain such datasets.

The current binary file extensions I consider include

- `.sas7bdat`
- `.sas7bcat`
- `.xpt`
- `xpt5`
- `xpt8`

Any other recommendations? @elong0527 

Note that some units tests might need an update for this change.

**Comment by elong0527** [comment]
It is comprehensive!

**Comment by nanxstats** [comment]
Fixed by https://github.com/Merck/pkglite/commit/47747121b72b557cfd3c045473118e1319a852b5
